name: Floaty Fighters

description: "Pay back your insurmountable debt to Mayor Onion, and tear down the corrupt vegetable government!"

markdown: kramdown

permalink: /blog/:title

trailer: "vLsoncRgaTs"

screenshots:
 - "/assets/screenshots/00.png"
 - "/assets/screenshots/01.png"
 - "/assets/screenshots/02.png"
 - "/assets/screenshots/03.png"
 - "/assets/screenshots/04.png"
 - "/assets/screenshots/05.png"
 - "/assets/screenshots/06.png"
 - "/assets/screenshots/07.png"
 - "/assets/screenshots/08.png"
 - "/assets/screenshots/09.png"
 - "/assets/screenshots/10.png"
 - "/assets/screenshots/11.png"
 - "/assets/screenshots/12.png"
 - "/assets/screenshots/13.png"
 - "/assets/screenshots/14.png"
 - "/assets/screenshots/15.png"

gems:
 - jekyll-sitemap