name: Floaty Fighters

description: "It's fight or flight! Battle it out in the sky as four unique combatants in this free movement fighting game!"

markdown: kramdown

permalink: /blog/:title

trailer: "0TLu3IUKE1w"

screenshots:
 - "/assets/screenshots/00.png"
 - "/assets/screenshots/01.png"
 - "/assets/screenshots/02.png"
 - "/assets/screenshots/03.png"
 - "/assets/screenshots/04.png"
 - "/assets/screenshots/05.png"
 - "/assets/screenshots/06.png"
 - "/assets/screenshots/07.png"
 - "/assets/screenshots/08.png"
 - "/assets/screenshots/09.png"
 - "/assets/screenshots/10.png"
 - "/assets/screenshots/11.png"
 - "/assets/screenshots/12.png"
 - "/assets/screenshots/13.png"

gems:
 - jekyll-sitemap